Updated Read me file
kcoder63/Eddiehub_share pull request #9
Opened 2021-03-20 14:39 UTC by rohank2502

Added few screenshots and updated the read me file

2021-03-20 15:25 UTC, rohank2502 commented
![Uploading Screenshot 2021-03-20 205433.png…]()
 It is looking like this !

2021-03-20 15:28 UTC, rohank2502 commented
![Screenshot 2021-03-20 205809](https://user-images.githubusercontent.com/76584243/111875285-fdd02400-89be-11eb-959e-ae828e6898e8.png)

2021-03-20 16:08 UTC, kcoder63 requested changes
better to remove the screenshot with your email in it, we can keep it empty or crop it out?

2021-03-20 16:08 UTC, kcoder63 commented on index.html
> +          <div class="item"><a href="#"><i class="fas fa-info-circle"></i>About</a></div>
why did you remove about.html?

2021-03-20 16:19 UTC, rohank2502 commented
>  to remove the screenshot with your email in it, we can keep it empty or crop it out?

I will make it blur will it be ok ?

2021-03-20 16:20 UTC, rohank2502 commented on index.html
> +          <div class="item"><a href="#"><i class="fas fa-info-circle"></i>About</a></div>
no I didnt by mistake might be will add it

2021-03-20 16:33 UTC, rohank2502 commented
> 
> 
> better to remove the screenshot with your email in it, we can keep it empty or crop it out?

Made those changes

2021-03-20 16:33 UTC, rohank2502 commented
![23](https://user-images.githubusercontent.com/76584243/111877186-15f87100-89c8-11eb-8af9-032d00f2cd1a.png)

2021-03-20 16:43 UTC, Vyvy-vi reviewed
Maybe you can deploy the github pages site on your account, so that we could view it?

2021-03-20 16:43 UTC, Vyvy-vi commented on README.md
>  Join EddieHub's discord server, where we geek out [here](https://discord.gg/PNHRZJf7v7)
```suggestion
Join EddieHub's discord server, where we geek out [here](http://discord.eddiehub.org)
```
Maybe using the permanent server link might be more manageable.

2021-03-20 16:44 UTC, rohank2502 commented on README.md
>  Join EddieHub's discord server, where we geek out [here](https://discord.gg/PNHRZJf7v7)
I dont added that links

2021-03-20 16:45 UTC, rohank2502 commented
> 
> 
> Maybe you can deploy the github pages site on your account, so that we could view it?

https://rohank2502.github.io/Eddiehub_share/

2021-03-20 19:01 UTC, SamDev98 approved these changes
LGTM

2021-03-21 03:02 UTC, kcoder63 commented
> Maybe you can deploy the github pages site on your account, so that we could view it?

I did

2021-03-21 03:03 UTC, kcoder63 approved these changes
LGTM

2021-03-21 03:03 UTC, merged